name: Run Colab notebook daily

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 오전 9시 KST (0시 UTC 기준)
  workflow_dispatch:

jobs:
  run-colab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install google-search-results notebook

      - name: Run notebook securely (serp_secure_push_final_v2)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          jupyter nbconvert --to notebook --execute serp_secure_push_final_v2.ipynb --output executed_notebook.ipynb


